image: node:16.8.0-stretch

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  - test-e2e
  
cache:
  paths:
    - node_modules/

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm install --force
    - npm run build

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - npm run test:unit

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
